### ISSUE TITLE
"ChatGPT Was Unable To Process The Response"

### ISSUE THREAD

**Issue by danvau7** [cirolini/genai-code-review#28]
See the following screenshot. I am getting error messages that read: `ChatGPT was unable to process the response about XYZ`:

![image](https://github.com/cirolini/chatgpt-github-actions/assets/58438633/2e21cd07-8a41-4c8b-b009-6d750af4a82e)

This action has the correct permissions to write comments to the PR. Also, it appears the OpenAI token is working as I created it with maximum permissions on the OpenAI side, and I can see it is hitting the OpenAI API on the usage page for the token. 

**QUESTION:** Any idea why I might be getting these responses?

This Github Action looks terrific and would love to be able to use it. 

The code I am using is as follows. I removed the "davinci" engine that is in the sample / readme as I was receiving warnings it was deprecated in the Github Action logs:

```
jobs:
    review-1:
        runs-on: ubuntu-latest
        name: ChatGPT Cirolini Code Review
        steps:
        - name: ChatGPT Cirolini Code Review
          uses: cirolini/chatgpt-github-actions@v1.3
          with:
            openai_api_key: ${{ secrets.openai_api_key }}
            github_token: ${{ secrets.GITHUB_TOKEN }}
            github_pr_id: ${{ github.event.number }}
            openai_engine: "gpt-3.5-turbo-1106"
            openai_temperature: 0.5
            openai_max_tokens: 2048
            mode: patch
```
